name: zioproto-kolla
version: master
summary: OpenStack Kolla
description: |
  Containers and deployment tools for operating
  OpenStack clouds.  

confinement: classic
grade: devel

apps:
  kolla-ansible:
    command: kolla-ansible
    aliases:
      - kolla-ansible
  kolla-build:
    command: kolla-build
    aliases:
      - kolla-build
  kolla-genpwd:
    command: kolla-genpwd
    aliases:
      - kolla-genpwd

parts:
  kolla:
    plugin: python
    python-version: python3
    source: https://github.com/zioproto/kolla
    source-type: git
    source-branch: master
    python-packages:
      - ansible
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/newton/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
  kolla-ansible:
    plugin: python
    python-version: python3
    source: https://github.com/zioproto/kolla-ansible
    source-type: git
    source-branch: master
    after:
      - kolla
