name: zioproto-kolla
version: master
summary: OpenStack Kolla
description: |
  Containers and deployment tools for operating
  OpenStack clouds.  

confinement: classic
grade: devel

apps:
  kolla-ansible:
    command: kolla-ansible
    aliases:
      - kolla-ansible
  kolla-build:
    command: kolla-build
    aliases:
      - kolla-build
  kolla-genpwd:
    command: kolla-genpwd
    aliases:
      - kolla-genpwd
  ansible-playbook:
    command: ansible-playbook
    aliases:
      - ansible-playbook

parts:
  kolla:
    plugin: python
    python-version: python2
    source: https://github.com/zioproto/kolla
    source-type: git
    source-branch: snap
    python-packages:
      - ansible
      - git+https://github.com/zioproto/kolla-ansible@snap
    constraints: https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
