name: zioproto-kolla
version: 3.0.2
summary: OpenStack Kolla
description: |
  Containers and deployment tools for operating
  OpenStack clouds.  

confinement: classic
grade: devel

apps:
  kolla-ansible:
    command: kolla-ansible
    aliases:
      - kolla-ansible
  kolla-build:
    command: kolla-build
    aliases:
      - kolla-build
  kolla-genpwd:
    command: kolla-genpwd
    aliases:
      - kolla-genpwd

parts:
  kolla:
    plugin: python
    python-version: python2
    source: https://github.com/zioproto/kolla
    source-type: git
    source-branch: stable/newton
    python-packages:
      - ansible
    build-packages:
      - libffi-dev
      - libssl-dev
